/**
 * @Author: LanHao
 * @Website:https://lanhaoo.club/
 * @Created_Date:9:57 PM_10/22/2019
 * @Magic_Power_Of_Code!
 */

package club.lanhaoo.chat;

import club.lanhaoo.chat.Classes.Message;
import club.lanhaoo.chat.Classes.UserSettings;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.Date;

public class SingleTalk {
    private JTextArea textArea_chat;
    private JPanel panel1;
    private JTextArea textArea_message;
    private JButton sendButton;
    private JLabel labelIp;

    public void openWindow(String IP, final UserSettings userSettings) {
        JFrame frame = new JFrame("SingleTalk");
        SingleTalk singleTalk = new SingleTalk();
        frame.setContentPane(singleTalk.panel1);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);

        final JTextArea jTextArea_chat = singleTalk.textArea_chat;
        jTextArea_chat.append("现在聊天对象: " + IP);

        final JLabel jLabel_other = singleTalk.labelIp;
        jLabel_other.setText(IP);

        frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        final JTextArea jTextArea_message = singleTalk.textArea_message;

        JButton jButton_send = singleTalk.sendButton;

        jButton_send.addMouseListener(new MouseListener() {

            public void mouseClicked(MouseEvent e) {


            }


            public void mousePressed(MouseEvent e) {


                String pure_message =
                        jTextArea_message.getText();



                if(pure_message.trim().equals("")){

                    return;

                }



                Message message =
                        new Message(
                                "PRIVATE",
                                "SINGLE_TALK",
                                pure_message
                        );



                //目标用户IP
                message.sendToClient(
                        jLabel_other.getText()
                );



                //发送到服务器
                if(message.send(userSettings)){


                    jTextArea_chat.append(
                            "\n我:"
                                    +pure_message
                    );


                    jTextArea_message.setText(null);


                }else{


                    jTextArea_chat.append(
                            "\n发送失败\n"
                    );


                }


            }



            public void mouseReleased(MouseEvent e) {


            }


            public void mouseEntered(MouseEvent e) {


            }


            public void mouseExited(MouseEvent e) {


            }

        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setPreferredSize(new Dimension(600, 400));
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setHorizontalScrollBarPolicy(31);
        scrollPane1.setVerticalScrollBarPolicy(20);
        panel1.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        textArea_chat = new JTextArea();
        textArea_chat.setEditable(false);
        textArea_chat.setLineWrap(true);
        textArea_chat.setWrapStyleWord(true);
        scrollPane1.setViewportView(textArea_chat);
        labelIp = new JLabel();
        labelIp.setText("Label");
        panel1.add(labelIp, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        sendButton = new JButton();
        sendButton.setText("Send");
        panel1.add(sendButton, new GridConstraints(1, 1, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane2 = new JScrollPane();
        scrollPane2.setHorizontalScrollBarPolicy(31);
        panel1.add(scrollPane2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        textArea_message = new JTextArea();
        textArea_message.setPreferredSize(new Dimension(0, 40));
        textArea_message.setWrapStyleWord(true);
        scrollPane2.setViewportView(textArea_message);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
